### ISSUE TITLE
Add oncletom/wp-less to Packagist

### ISSUE THREAD

**Issue by mrgrain** [oncletom/wp-less#101]
This package already uses a `composer.json` file to manage its dependencies. Publishing it to [Packagist](https://packagist.org/) would make it available as a dependency itself.

Also, it's very easy to publish a package on Packagist.

**Comment by oncletom** [comment]
@mrgrain thanks for the hat tip: I thought a composer file was enough.

The package is now available and linked to the repo to enable auto-updates :-)
> https://packagist.org/packages/oncletom/wp-less

Thanks a lot for the props!
