### ISSUE TITLE
Embedding into a Theme

### ISSUE THREAD

**Issue by alvinkonda** [oncletom/wp-less#104]
Hi,

Im embedding WP Less plugin into the theme , its works perfect, the only issue it seems that it doesn't cache the css file generated. 

Any idea what im missing?

my code inside my functions.php is as following:

```
// WP Less initialize 
define('WP_LESS_COMPILATION', 'deep');

$less = WPLessPlugin::getInstance();
$less->dispatch();
```

**Comment by officialtheme** [comment]
Also in case you want to quickly test here is our WP theme ready with WP-Less built in

https://github.com/officialtheme/official-flowershop

**Comment by pixelbart** [comment]
Closed, due to age. If the problem persists, please reopen the issue.

Always make sure that `WP_DEBUG` is not set to true, otherwise the files will be regenerated again and again.
