### ISSUE TITLE
Mixins with multiple arguments

### ISSUE THREAD

**Issue by beyondtheline** [oncletom/wp-less#106]
Hi,
I got an issue with a mixin for multiple arguments that use regex to separeate the arguments by comma.

> .transition (@value1,@value2:X,...) {
>     @value: ~`"@{arguments}".replace(/[\[\]]|\,\sX/g, '')`;
> 
> ```
> -webkit-transition: @value;
> -moz-transition: @value;
> -ms-transition: @value;
> -o-transition: @value;
> transition: @value;
> ```
> 
> }

The compiled css says

> -webkit-transition: /\* Sorry, can not do JavaScript evaluation in PHP... :( _/;
> -moz-transition: /_ Sorry, can not do JavaScript evaluation in PHP... :( _/;
> -ms-transition: /_ Sorry, can not do JavaScript evaluation in PHP... :( _/;
> -o-transition: /_ Sorry, can not do JavaScript evaluation in PHP... :( _/;
> transition: /_ Sorry, can not do JavaScript evaluation in PHP... :( */;

Any Ideas for a Workaround? Should I do the replacement with PHP?

Thanks so far

**Comment by pixelbart** [comment]
Closed, due to age. If the problem persists, please reopen the issue.
