### ISSUE TITLE
Combine Less Files

### ISSUE THREAD

**Issue by ramachandranv** [oncletom/wp-less#109]
Is there a way to combine all less files to a single file. Or is there any plugin to do this.

**Comment by oncletom** [comment]
Well, the easiest way would be to do that either via another plugin (eg: [merge-minify-refresh](https://wordpress.org/plugins/merge-minify-refresh/) or by importing Less files into a single sheet:

```less
@import 'a.less';
@import 'b.less';
```

**Comment by pixelbart** [comment]
Closed, due to age. If the problem persists, please reopen the issue.
