### ISSUE TITLE
Recompiling Not Working

### ISSUE THREAD

**Issue by brandonlang** [oncletom/wp-less#114]
It feels like this project has been abandoned but hopefully someone happens to see this message.

I installed this plugin on my new Wordpress site running the latest version of Wordpress (4.6.1). I downloaded and installed directly through the Plugins interface which, I'm assuming, downloads from wordpress.org. So the plugin version that I have installed is 1.8.0.

I followed the information in the docs. Everything seemed to be working great up to the point where it appears that recompilation is not happening as expected. The docs mention that the default setting is "deep" compilation which looks for changes on enqueued files and any imported files. Compilation runs successfully anytime that I change an enqueued file, but NOT when I modify any of the imported files.

I've been playing with the configuration. In my wp-config.php file, I've set the following parameters...

`define( 'WP_DEBUG', true );
define( 'WP_LESS_ALWAYS_RECOMPILE', true );`

... but this does not seem to change the behavior. I have also tried this parameter...

`define( 'WP_LESS_COMPILATION', 'always' );`

... but, again, no changes. The only way I can force a recompilation is by directly modifying an enqueued file.

Any ideas what could be the problem or what I could investigate next? Aside from this issue, I'm so far loving this plugin!

Thanks!

**Comment by Xayaan** [comment]
Hey man. 

Are you sure its the compilation? So far it seems very much compatible. I encountered the issue of recompilation when i modified the theme folder name from "foodpicky" to my own. And when i changed it back, it fixed the issue, turns out that the file name on the LESS folder needs to be changed as well. 

Hope this helps!

**Comment by brandonlang** [comment]
Thanks for the reply. I couldn't figure out a solution so I ended up going with a SASS plugin instead. But hopefully this helps someone else.

**Comment by pixelbart** [comment]
Closed, due to age. If the problem persists, please reopen the issue.
