### ISSUE TITLE
How to set Upload Dir and set Upload Url correctly?

### ISSUE THREAD

**Issue by khanhtd1108** [oncletom/wp-less#115]
I have an issue:
My less: "mytheme/css/less/bootstrap.less"
try: $lessConfig->setUploadDir(get_stylesheet_directory() . '/css');
My css file is compiled in "mytheme/css/mytheme/css/less/bootstrap-4567bbc3.css"
I want to set compiled css file put in css folder like this "mytheme/css/bootstrap-4567bbc3.css"
So how can i do this?

**Comment by pixelbart** [comment]
Closed, due to age. If the problem persists, please reopen the issue.
