### ISSUE TITLE
Debug Mode: Warnings in TinyMCE

### ISSUE THREAD

**Issue by DavidSteinbauer** [oncletom/wp-less#116]
hi,

i see warnings in every of my wp-less installation when i'm in debug mode.

Hope that helps, thanks!!:

```
Notice: Undefined index: scheme in /plugins/wp-less/lib/Plugin.class.php on line 308
Notice: Undefined index: host in /plugins/wp-less/lib/Plugin.class.php on line 308
Notice: Undefined index: extension in /plugins/wp-less/lib/Plugin.class.php on line 312
```

![2018-05-16 at 15 07](https://user-images.githubusercontent.com/3392092/40118819-458c634e-591b-11e8-8ccc-928cdd6d17d7.jpg)

**Comment by pixelbart** [comment]
Closed, due to age. If the problem persists, please reopen the issue.
