### ISSUE TITLE
composer vendor directory missing from WordPress package

### ISSUE THREAD

**Issue by strivedev** [oncletom/wp-less#118]
```PHP Warning:  require(/www/site/public/wp-content/plugins/wp-less/lib/../vendor/wikimedia/less.php/lessc.inc.php): failed to open stream: No such file or directory in /www/site/public/wp-content/plugins/wp-less/lib/Plugin.class.php on line 50```

The automated deploy to WordPress does not run `composer install` so there is no vendor directory / packages available in the WordPress plugin.

https://github.com/oncletom/wp-less/blob/7ecdfb240fd909c552e0f92d80cc8f61234bbfff/.github/workflows/wordpress.yml#L11-L15

Adding something like this in between checkout and deploy will probably be enough.
```
- name: Build
  run: composer install
```

**Comment by pixelbart** [comment]
@oncletom

Here we have forgotten the composer install or composer update. I am quite new to Github Actions, so I can't quite verify that this is correct.

**Comment by strivedev** [comment]
Confirming this is fixed as of 7dab83b48d95c3c08c8e7d9a930246f0f261f60c / 1.9.3-3

**Comment by oncletom** [comment]
Thanks for raising the issue, and sorry for having missed this detail.

And thanks @pixelbart to have triggered this plugin update!
