### ISSUE TITLE
WP-less does not generate new stylesheet all of sudden

### ISSUE THREAD

**Issue by unfulvio** [oncletom/wp-less#33]
I'm using wp-less as a plugin. wp-less is not generating new stylesheets - it keeps embedding in the header the last one; I deleted the folder under uploads/wp-less and did a few edits to my .less stylesheet, but still it doesn't generate a new css file and keep an old reference in wp-header to a generated css file that no longer exists; I tried deactivating and reactivating the plugin, overwriting with files downloaded from this repo, to no avail. I did not install new plugins or updated existing ones for the problem to appear. I had made few edits to a less stylesheet yesterday night and uploaded it only this morning. That's probably when the problem occurred for the first time. I reverted back the changes, but the new stylesheet is not generated any more. I tried to make the less stylesheet empty with just a single style (like body { color: red } ) to no avail.

**Comment by kaiserkhan** [comment]
how to solve this issue:Catchable fatal error: Argument 1 passed to Ozpital\WPWeTransfer\Core\OWPWT_Option::register() must be an instance of Ozpital\WPWeTransfer\Core\String, string given, called in /home/imraumqv/public_html/orbitgraphics/wp-content/plugins/ozpital-wetransfer/app/Core/OWPWT_Option.php on line 56 and defined in /home/imraumqv/public_html/orbitgraphics/wp-content/plugins/ozpital-wetransfer/app/Core/OWPWT_Option.php on line 22

**Comment by pixelbart** [comment]
Closed, due to age. If the problem persists, please reopen the issue.
