### ISSUE TITLE
Compressing CSS Output

### ISSUE THREAD

**Issue by corradomatt** [oncletom/wp-less#43]
I should probably open a pull request for this but I'm not sure how many others want/need it. In Plugin.class.php around line 43 I added this to the construct...
```php
$this->compiler->setFormatter('compressed');
```
It ecentially minifies the css output. It didn't make a huge difference on file size for me but I figure every k counts!

So, to recap, line 43....
```php
        $this->compiler = new WPLessCompiler;
        $this->compiler->setFormatter('compressed');
        $this->compiler->setVariable('stylesheet_directory_uri', "'" . get_stylesheet_directory_uri() . "'");
        $this->compiler->setVariable('template_directory_uri', "'" . get_template_directory_uri() . "'");
```

It's easy to read the output css file without this obviously but better to have this for mobile reasons.

**Comment by vweevers** [comment]
-1 for `WP_LESS_COMPRESS` configuration madness, and -1 for option pages with a maintenance burden. As a consumer, simply do:

```php
$less = WPLessPlugin::getInstance();
$less->getCompiler()->setFormatter('compressed');
```

But I do agree it should be the default formatter. Proposal for `Plugin.class.php`:

```php
if (!defined('WP_DEBUG') || !WP_DEBUG) {
  $this->setFormatter('compressed');
}
```

**Comment by tyrann0us** [comment]
@corradomatt, why has this been closed?
