### ISSUE TITLE
Problem with Comments in output file

### ISSUE THREAD

**Issue by rezat42** [oncletom/wp-less#69]
Hey,
 I'm using wp-less, and all comments in generated css's are eliminated, how can i set it to output comments?

**Comment by babobski** [comment]
If you want to only output one comment block (like the comment block in you're style.css declaring you're theme) you can use this 
```
/*!
this comment block will not be removed because of the !
*/
```

**Comment by oncletom** [comment]
@babobski is it an "official" less syntax or a hack/workaround less syntax?

**Comment by pixelbart** [comment]
Closed, due to age. If the problem persists, please reopen the issue.
