### ISSUE TITLE
Doesn't appear to work in WP 4.3.1?

### ISSUE THREAD

**Issue by RKS213** [oncletom/wp-less#93]
Have a fresh install of WordPress 4.3.1 and installed this module. In functions I've tried a bunch of different combinations of enqueue and it continues to set it as "text/css" instead of "text/less."

wp_enqueue_style('mytheme-less', get_stylesheet_directory_uri().'/css/style.less');

**Comment by oncletom** [comment]
What do you mean by *it continues to set it as "text/css"*?

**Comment by RKS213** [comment]
Nothing. There was an error in the theme functions that caused an error with the output of the less. It was preventing the proper <link> tag from creating. All good now.

**Comment by oncletom** [comment]
:+1:
