### ISSUE TITLE
WP LESS breaks tinyMCE

### ISSUE THREAD

**Issue by WIWIWWII** [oncletom/wp-less#94]
I don't know why or how. But using the latest version 1.8 of LESS with Wordpress 4.3.1 breaks all the tinyMCE editors in Wordpress. TinyMCE is unable to add styling. 

Working locally using MAMP, im getting the following errors in Chrome: 

`http://localhost/XX/wp-includes/css/dashicons.min.css?wp-mce-4205-20150910 Failed to load resource: net::ERR_CONNECTION_REFUSED`

`http://localhost/XX/wp-includes/js/tinymce/skins/wordpress/wp-content.css?wp-mce-4205-20150910 Failed to load resource: net::ERR_CONNECTION_REFUSED`

in Firefox:
`Use of Mutation Events is deprecated. Use MutationObserver instead.`

It is not theme related (switching theme's will have same effect, even when theme is not supporting LESS). When deactivating WP LESS, the editor works again.
Thanks!

**Comment by fabrizim** [comment]
The only hook that less has into the editor is the mce_css filter (https://github.com/oncletom/wp-less/blob/master/lib/Plugin.class.php#L287). Are you adding a '.less' stylesheet to the editor? If so, if there are errors in the less file, the html output might be ending at the editor.

The Firefox error is not relevant. The other errors indicate that core Wordpress files are not accessible. Can you see the css files if you paste those urls into your browser?

**Comment by WIWIWWII** [comment]
Thanks for getting back this soon and looking in to this! There are no errors in the .less file, currently I use the regular hook to add CSS to the editor.

'add_editor_style('css/editor-style.css');'

Removing the 'wp_enqueue_style' hooks that add my less files doesn't result in the editor having the correct CSS. The only thing that will make CSS in the editor work, is deactivating the WP-LESS plugin. 

You are right on one part. Although all my files have the path 'localhost:8888/', the editor-file points to 'localhost/'. But only when the plugin is activated. I've looked into the hooks of WP-LESS but can't find anything that could relate to this problem.
Thanks again for your time!

**Comment by WIWIWWII** [comment]
I figured out that this line doesn't seem to work nice when using regular localhost settings on MAMP:

`$style_sheet = $parts['scheme'] . '://' . $parts['host'] . $parts['path'];`

This is a quick fix for my problem:

`$style_sheet = $parts['scheme'] . '://' . $parts['host'] . ':8888' . $parts['path'];`

Not a big deal for development, I'll remove the "8888" addition in production.

**Comment by oncletom** [comment]
This could do the trick:

```php
$style_sheet = $parts['scheme'] . '://' . $parts['host'] . ($parts['port'] ?: ':' . $parts['port']) .  $parts['path'];
```

**Comment by WIWIWWII** [comment]
Worked great, thank you great Oncletom!

**Comment by fabrizim** [comment]
FYI - I just adjusted that new code a bit as it was breaking for sites on default ports (80,443). See be3fffedd1c0eba35642407d228a9976c7b08d5f
