### ISSUE TITLE
Undefined with brook tamplte

### ISSUE THREAD

**Issue by NeoCsatornaja** [oncletom/wp-less#95]
Fatal error: Uncaught exception 'Less_Exception_Compiler' with message 'variable @color_grey_sidebar is undefined in file ...themes/brook/stylesheet/less/colors.less in colors.less on line 8, column 16 06| @grey-pale: @color_grey_pale; 07| @grey-light: @color_grey_light; 08| @grey-sidebar: @color_grey_sidebar; 09| @grey: @color_grey; 10| @black: @color_black; 11| ' in .../wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Tree/Variable.php:49 Stack trace: #0 ...wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Tree/Expression.php(52): Less_Tree_Variable->compile(Object(Less_Environment)) #1 .../wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Tree/Value.php(27): Less_Tree_Expression->compile(Object(Less_Environment)) #2.../wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Tree/Rule.php(75): Less_Tree_Value->compile(Object(Less in ...wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Tree/Variable.php on line 49

**Comment by oncletom** [comment]
Hi @NeoCsatornaja, the error is quite explicit: it says the variable `@color_grey_sidebar` is not defined.

Eventually read the guidelines of the theme, in case it is a mandatory setup :-)

Let us know how it goes :+1:

**Comment by pixelbart** [comment]
Closed, due to age. If the problem persists, please reopen the issue.
