### ISSUE TITLE
Fatal error: Uncaught exception 'Less_Exception_Chunk'

### ISSUE THREAD

**Issue by bossev** [oncletom/wp-less#98]
Fatal error: Uncaught exception 'Less_Exception_Chunk' with message 'ParseError: missing closing `*/` in layout.less on line 371, column 3 369| } 370| 371| } /* /media query  372| ' in /home/www/79ideas.org/wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Parser.php:535 Stack trace: #0 /home/www/79ideas.org/wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Parser.php(343): Less_Parser->GetRules('/home/www/79ide...') #1 /home/www/79ideas.org/wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Tree/Import.php(277): Less_Parser->parseFile('/home/www/79ide...', '', true) #2 /home/www/79ideas.org/wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Tree/Import.php(193): Less_Tree_Import->ParseImport('/home/www/79ide...', '', Object(Less_Environment)) #3 /home/www/79ideas.org/wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Tree/Ruleset.php(248): Less_Tree_Import->compile(Object(Less_Environment)) #4 /home/www/79ideas.org/wp-content/plugins/wp-less/vendor/oyejorge/less.p in /home/www/79ideas.org/wp-content/plugins/wp-less/vendor/oyejorge/less.php/lib/Less/Parser.php on line 535

**Comment by bossev** [comment]
this is probably for oyejorge/less.php

**Comment by oncletom** [comment]
@bossev I guess so. Forward the issue here if it happens not to be the case :-)
