### ISSUE TITLE
Notice: Undefined index: extension

### ISSUE THREAD

**Issue by mikedidthis** [oncletom/wp-less#99]
Using `wp_editor` and the plugin `wp-less` causes the following notice:

> Notice: Undefined index: extension in E:\WebMatrix\wp-base\wp-content\plugins\wp-less\lib\Plugin.class.php on line 312

If you disable `tinymce` being used with `wp_editor`:

```
<?php wp_editor( html_entity_decode( $this->options['text'] ), 'wp_ultramessage_text', array(
    'textarea_name' => "$this->plugin_name[text]",
    'tinymce' => false,
) ); ?>
```

Or disable `wp-less` the notice stops.

**Comment by pixelbart** [comment]
Closed, due to age. If the problem persists, please reopen the issue.
